# Generated by Django 3.2.5 on 2021-09-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(default='', max_length=10)),
                ('UserName', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
